CREATE DATABASE WEATHER_DB;

USE DATABASE WEATHER_DB;

CREATE SCHEMA WEATHER_SCHEMA;

USE SCHEMA WEATHER_SCHEMA;

CREATE OR REPLACE TABLE CURRENT_DATA (
    CITY STRING,
    REGION STRING,
    COUNTRY STRING,
    TEMP_C FLOAT,
    FEELSLIKE_C FLOAT,
    HUMIDITY FLOAT,
    WIND_KPH FLOAT,
    PRESSURE_MB FLOAT,
    PRECIP_MM FLOAT,
    VIS_KM FLOAT,
    UV FLOAT,
    AQI_CO FLOAT,
    AQI_NO2 FLOAT,
    AQI_O3 FLOAT,
    AQI_SO2 FLOAT,
    AQI_PM2_5 FLOAT,
    AQI_PM10 FLOAT,
    LAST_UPDATED TIMESTAMP
);